# Generated by Django 4.2.1 on 2023-07-03 18:31

import apps.courses.custom_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order', apps.courses.custom_fields.OrderField(blank=True, help_text='Order of the content')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'db_table': 'contents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation', verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date and time of modification', verbose_name='Modified')),
                ('title', models.CharField(help_text='Title of the course', max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Slug of the course', max_length=200, unique=True, verbose_name='Slug')),
                ('overview', models.TextField(help_text='Course overview', verbose_name='Overview')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation', verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date and time of modification', verbose_name='Modified')),
                ('title', models.CharField(help_text='Title of the item', max_length=200, verbose_name='Title')),
                ('file', models.FileField(help_text='File', upload_to='files', verbose_name='File')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation', verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date and time of modification', verbose_name='Modified')),
                ('title', models.CharField(help_text='Title of the item', max_length=200, verbose_name='Title')),
                ('image', models.FileField(help_text='Image', upload_to='images', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation', verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date and time of modification', verbose_name='Modified')),
                ('title', models.CharField(help_text='Title of the module', max_length=200, verbose_name='Title')),
                ('description', models.TextField(help_text='Description of the module', verbose_name='Description')),
                ('order', apps.courses.custom_fields.OrderField(blank=True, help_text='Order of the module')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation', verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date and time of modification', verbose_name='Modified')),
                ('title', models.CharField(help_text='Title of the subject', max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Slug of the subject', max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Description of the subject', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation', verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date and time of modification', verbose_name='Modified')),
                ('title', models.CharField(help_text='Title of the item', max_length=200, verbose_name='Title')),
                ('content', models.TextField(help_text='Content of the text', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Text',
                'verbose_name_plural': 'Texts',
                'db_table': 'texts',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation', verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date and time of modification', verbose_name='Modified')),
                ('title', models.CharField(help_text='Title of the item', max_length=200, verbose_name='Title')),
                ('url', models.URLField(help_text='URL of the video', verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'videos',
            },
        ),
    ]
