# Generated by Django 4.2.1 on 2023-06-05 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation', verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date and time of modification', verbose_name='Modified')),
                ('title', models.CharField(help_text='Title of the course', max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Slug of the course', max_length=200, unique=True, verbose_name='Slug')),
                ('overview', models.TextField(help_text='Course overview', verbose_name='Overview')),
                ('prerequisites', models.TextField(help_text='Course prerequisites', verbose_name='Prerequisites')),
                ('duration', models.DurationField(help_text='Course duration', verbose_name='Duration')),
                ('instructor', models.ForeignKey(help_text='Instructor of the course', on_delete=django.db.models.deletion.CASCADE, related_name='courses_created', to=settings.AUTH_USER_MODEL, verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation', verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date and time of modification', verbose_name='Modified')),
                ('title', models.CharField(help_text='Title of the subject', max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Slug of the subject', max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='Description of the subject', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation', verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date and time of modification', verbose_name='Modified')),
                ('title', models.CharField(help_text='Title of the module', max_length=200, verbose_name='Title')),
                ('description', models.TextField(help_text='Description of the module', verbose_name='Description')),
                ('course', models.ForeignKey(help_text='Course linked to the module', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'modules',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(help_text='Subject of the course', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.subject', verbose_name='Subject'),
        ),
    ]
