# Generated by Django 4.2.1 on 2023-06-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the subject', null=True, verbose_name='Description'),
        ),
    ]
