# Generated by Django 4.2.1 on 2023-06-05 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_alter_subject_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation', verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date and time of modification', verbose_name='Modified')),
                ('title', models.CharField(help_text='Title of the item', max_length=200, verbose_name='Title')),
                ('url', models.URLField(help_text='URL of the video', verbose_name='URL')),
                ('owner', models.ForeignKey(help_text='User who created the content', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation', verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date and time of modification', verbose_name='Modified')),
                ('title', models.CharField(help_text='Title of the item', max_length=200, verbose_name='Title')),
                ('content', models.TextField(help_text='Content of the text', verbose_name='Content')),
                ('owner', models.ForeignKey(help_text='User who created the content', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Text',
                'verbose_name_plural': 'Texts',
                'db_table': 'texts',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation', verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date and time of modification', verbose_name='Modified')),
                ('title', models.CharField(help_text='Title of the item', max_length=200, verbose_name='Title')),
                ('image', models.ImageField(help_text='Image', upload_to='images', verbose_name='Image')),
                ('owner', models.ForeignKey(help_text='User who created the content', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation', verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date and time of modification', verbose_name='Modified')),
                ('title', models.CharField(help_text='Title of the item', max_length=200, verbose_name='Title')),
                ('file', models.FileField(help_text='File', upload_to='files', verbose_name='File')),
                ('owner', models.ForeignKey(help_text='User who created the content', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'image', 'file')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.module')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'db_table': 'contents',
            },
        ),
    ]
