# Generated by Django 4.2.1 on 2023-06-05 17:53

import apps.courses.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_video_text_image_file_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order'], 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=apps.courses.custom_fields.OrderField(blank=True, default=0, help_text='Order of the content', verbose_name='Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=apps.courses.custom_fields.OrderField(blank=True, default=0, help_text='Order of the module', verbose_name='Order'),
            preserve_default=False,
        ),
    ]
